version: "3.8"
services:
  redis:
    image: redis:7
    restart: unless-stopped
    volumes:
      - redis-data:/data

  textbelt:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - redis
    ports:
      - "9090:9090"
    environment:
      - PORT=9090
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_SECURE=${SMTP_SECURE}
      - FROM_EMAIL=${FROM_EMAIL}
    volumes:
      - ./lib:/app/lib
volumes:
  redis-data:
